import {
  Ledger,
  Party,
  ContractId,
  CreateEvent,
  Event,
  Decimal,
  Int,
} from "@c7/ledger";

// These types are assumed to be generated by `dpm codegen-js`.
// The path depends on the project's `name` and `version` in `daml.yaml`.
import {
  Market,
  PostLendOffer,
  PostBorrowOffer,
  MatchOffers,
} from "@daml.js/canton-fixed-rate-lending-0.1.0/lib/Lending/Market";
import {
  LendOffer,
  Cancel as CancelLendOffer,
} from "@daml.js/canton-fixed-rate-lending-0.1.0/lib/Lending/OrderBook";
import {
  BorrowOffer,
  Cancel as CancelBorrowOffer,
} from "@daml.js/canton-fixed-rate-lending-0.1.0/lib/Lending/OrderBook";
import {
  LoanAgreement,
  Repay,
} from "@daml.js/canton-fixed-rate-lending-0.1.0/lib/Lending/LoanAgreement";

/**
 * Represents the parameters for posting a new lend offer to the market.
 */
export interface PostLendOfferArgs {
  amount: Decimal;
  interestRate: Decimal;
  tenorDays: Int;
  id: string; // User-provided unique identifier for the offer
}

/**
 * Represents the parameters for posting a new borrow offer to the market.
 */
export interface PostBorrowOfferArgs {
  amount: Decimal;
  interestRate: Decimal;
  tenorDays: Int;
  collateralAsset: string; // Identifier for the collateral asset (e.g., ISIN)
  collateralQuantity: Decimal;
  id: string; // User-provided unique identifier for the offer
}

/**
 * Represents the parameters for matching a lend and borrow offer.
 * This action is typically performed by the market operator.
 */
export interface MatchOffersArgs {
  lendOfferCid: ContractId<LendOffer>;
  borrowOfferCid: ContractId<BorrowOffer>;
}

/**
 * Represents the parameters for repaying a loan.
 */
export interface RepayLoanArgs {
  loanAgreementCid: ContractId<LoanAgreement>;
  // The repayment logic in Daml will use this to find the payment token
  // contract from the borrower's wallet to fulfill the repayment.
  repaymentAmount: Decimal;
}

/**
 * A TypeScript SDK for interacting with the Canton Fixed-Rate Lending application.
 * This client simplifies creating and exercising choices on the Daml contracts.
 */
export class LendingClient {
  private readonly ledger: Ledger;
  private readonly party: Party;
  private readonly market: Party;

  /**
   * Constructs a new LendingClient instance.
   * @param ledger An initialized `@c7/ledger` instance.
   * @param party The party ID of the user operating the client.
   * @param market The party ID of the market operator.
   */
  constructor(ledger: Ledger, party: Party, market: Party) {
    this.ledger = ledger;
    this.party = party;
    this.market = market;
  }

  /**
   * Retrieves the singleton Market contract, which is the entry point for most actions.
   * Throws an error if the Market contract is not found.
   * @returns A promise that resolves to the created event of the Market contract.
   */
  private async getMarketContract(): Promise<CreateEvent<Market>> {
    const marketContracts = await this.ledger.query(Market.template(), {
      operator: this.market,
    });
    if (marketContracts.length === 0) {
      throw new Error(
        `Market contract not found for operator ${this.market}. Ensure it has been initialized.`
      );
    }
    if (marketContracts.length > 1) {
      console.warn(
        `Multiple Market contracts found for operator ${this.market}. Using the first one.`
      );
    }
    return marketContracts[0];
  }

  /**
   * Posts a lend offer to the order book via the market.
   * @param args The parameters for the lend offer.
   * @returns A promise that resolves to the result of the exercise choice.
   */
  public async postLendOffer(args: PostLendOfferArgs): Promise<Event<LendOffer>[]> {
    const marketContract = await this.getMarketContract();
    const choiceArgs: PostLendOffer = {
      lender: this.party,
      offerId: args.id,
      amount: args.amount,
      interestRate: args.interestRate,
      tenorDays: args.tenorDays,
    };
    return this.ledger.exercise(
      Market.PostLendOffer,
      marketContract.contractId,
      choiceArgs
    );
  }

  /**
   * Posts a borrow offer to the order book via the market.
   * @param args The parameters for the borrow offer.
   * @returns A promise that resolves to the result of the exercise choice.
   */
  public async postBorrowOffer(
    args: PostBorrowOfferArgs
  ): Promise<Event<BorrowOffer>[]> {
    const marketContract = await this.getMarketContract();
    const choiceArgs: PostBorrowOffer = {
      borrower: this.party,
      offerId: args.id,
      amount: args.amount,
      interestRate: args.interestRate,
      tenorDays: args.tenorDays,
      collateral: {
        assetId: args.collateralAsset,
        quantity: args.collateralQuantity,
      },
    };
    return this.ledger.exercise(
      Market.PostBorrowOffer,
      marketContract.contractId,
      choiceArgs
    );
  }

  /**
   * Cancels an active LendOffer.
   * @param lendOfferCid The ContractId of the LendOffer to cancel.
   * @returns A promise that resolves to the archival event.
   */
  public async cancelLendOffer(
    lendOfferCid: ContractId<LendOffer>
  ): Promise<Event<LendOffer>[]> {
    const choiceArgs: CancelLendOffer = {};
    return this.ledger.exercise(
      LendOffer.Cancel,
      lendOfferCid,
      choiceArgs
    );
  }

  /**
   * Cancels an active BorrowOffer.
   * @param borrowOfferCid The ContractId of the BorrowOffer to cancel.
   * @returns A promise that resolves to the archival event.
   */
  public async cancelBorrowOffer(
    borrowOfferCid: ContractId<BorrowOffer>
  ): Promise<Event<BorrowOffer>[]> {
    const choiceArgs: CancelBorrowOffer = {};
    return this.ledger.exercise(
      BorrowOffer.Cancel,
      borrowOfferCid,
      choiceArgs
    );
  }

  /**
   * Matches a lend offer with a borrow offer to create a LoanAgreement.
   * This method should typically be called by the market operator.
   * @param args The contract IDs of the lend and borrow offers to match.
   * @returns A promise that resolves to the events resulting from the match,
   *          including the creation of the LoanAgreement and CollateralVault.
   */
  public async matchOffers(
    args: MatchOffersArgs
  ): Promise<Event<LoanAgreement>[]> {
    const marketContract = await this.getMarketContract();
    const choiceArgs: MatchOffers = {
      lendOfferCid: args.lendOfferCid,
      borrowOfferCid: args.borrowOfferCid,
    };
    return this.ledger.exercise(
      Market.MatchOffers,
      marketContract.contractId,
      choiceArgs
    );
  }

  /**
   * Repays a loan, either partially or in full.
   * This is called by the borrower.
   * @param args The contract ID of the loan and the amount to repay.
   * @returns A promise that resolves to the events from the repayment.
   */
  public async repayLoan(args: RepayLoanArgs): Promise<Event<LoanAgreement>[]> {
    const choiceArgs: Repay = {
      repaymentAmount: args.repaymentAmount,
    };
    return this.ledger.exercise(
      LoanAgreement.Repay,
      args.loanAgreementCid,
      choiceArgs
    );
  }

  /**
   * Queries for all active lend offers created by the current party.
   * @returns A promise that resolves to an array of active LendOffer contracts.
   */
  public async getMyLendOffers(): Promise<CreateEvent<LendOffer>[]> {
    return this.ledger.query(LendOffer.template(), { lender: this.party });
  }

  /**
   * Queries for all active borrow offers created by the current party.
   * @returns A promise that resolves to an array of active BorrowOffer contracts.
   */
  public async getMyBorrowOffers(): Promise<CreateEvent<BorrowOffer>[]> {
    return this.ledger.query(BorrowOffer.template(), { borrower: this.party });
  }

  /**
   * Queries for all active loan agreements where the current party is either
   * the lender or the borrower.
   * @returns A promise that resolves to an array of active LoanAgreement contracts.
   */
  public async getMyLoanAgreements(): Promise<CreateEvent<LoanAgreement>[]> {
    const asLender = this.ledger.query(LoanAgreement.template(), {
      lender: this.party,
    });
    const asBorrower = this.ledger.query(LoanAgreement.template(), {
      borrower: this.party,
    });
    const [lenderLoans, borrowerLoans] = await Promise.all([
      asLender,
      asBorrower,
    ]);
    return [...lenderLoans, ...borrowerLoans];
  }

  /**
   * Queries for all active lend offers on the market.
   * @returns A promise that resolves to an array of all active LendOffer contracts.
   */
  public async getAllLendOffers(): Promise<CreateEvent<LendOffer>[]> {
    return this.ledger.query(LendOffer.template());
  }

  /**
   * Queries for all active borrow offers on the market.
   * @returns A promise that resolves to an array of all active BorrowOffer contracts.
   */
  public async getAllBorrowOffers(): Promise<CreateEvent<BorrowOffer>[]> {
    return this.ledger.query(BorrowOffer.template());
  }
}